export { default as Login } from "./Login"
export { default as Register } from "./Register"
export { default as DashboardUser } from "./user/Dashboard"
export { default as NotFoundPage } from "./NotFoundPage"
export { default as ForbiddenPage } from "./ForbiddenPage"